name: GALLANT-WS3
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - geopandas
  - shapely
  - pyproj
  - rtree
  - fiona
  - gdal
  - rasterio
  - tqdm 
  - openpyxl
  - geodatasets
  - python-dateutil
  - pytorch
  - peft
  - openai
  - faiss-cpu
  - msal
  - requests
  - pillow
  - sentence-transformers
  - pip
  - pip:
      - transformers
      - datasets
      - diffusers   
